# -*- coding: utf-8 -*-
"""Assignment_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYYVffCBxbCEsgFPHH5VsdCZdvYwLg_E
"""

!pip install diffusers transformers accelerate torch

from diffusers import StableDiffusionPipeline
import torch

# Load the pretrained model
pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
)

pipe = pipe.to("cuda")

prompt = "A perfect Sniper Rifle"

image = pipe(prompt).images[0]

image

